version: '3.9'

services:
  postgres:
      image: postgres:15
      container_name: mortgage-db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: mortgage_decisioning
      ports:
        - "5432:5432"
      volumes:
        - ./database/init.sql:/docker-entrypoint-initdb.d/01_init.sql
        - ./dataset/training_data.csv:/docker-entrypoint-initdb.d/training_data.csv
        - ./dataset/users.csv:/docker-entrypoint-initdb.d/users.csv
        - ./dataset/rules_config.csv:/docker-entrypoint-initdb.d/rules_config.csv
        - ./database/load_data.sql:/docker-entrypoint-initdb.d/02_load_data.sql

  borrowers-helper-service:
    build:
      context: ./services/borrowers-helper-service
    env_file:
      - .env
    environment:
      - SERVICE_NAME=borrowers-helper-service
    depends_on:
      - postgres
    ports:
      - "8001:8000"

  decision-coordinator-service:
    build:
      context: ./services/decision-coordinator-service
    env_file:
      - .env
    environment:
      - SERVICE_NAME=decision-coordinator-service
    depends_on:
      - postgres
    ports:
      - "8002:8000"
  
  rule-engine-service:
    build:
      context: ./services/rule-engine-service
    env_file:
      - .env
    environment:
      - SERVICE_NAME=rule-engine-service
    depends_on:
      - postgres
    ports:
      - "8003:8000"

  ml-decision-service:
    build:
      context: ./services/ml-decision-service
    env_file:
      - .env
    environment:
      - SERVICE_NAME=ml-decision-service
    depends_on:
      - postgres
    volumes:
      - ./services/ml-decision-service/app:/app
    ports:
      - "8004:8000"  
  
  fairness-auditor-service:
    build:
      context: ./services/fairness-auditor-service
    env_file:
      - .env
    environment:
      - SERVICE_NAME=fairness-auditor-service
    depends_on:
      - postgres
    ports:
      - "8005:8000"      

  underwriter-helper-service:
    build:
      context: ./services/underwriter-helper-service
    env_file:
      - .env
    environment:
      - SERVICE_NAME=underwriter-helper-service
    depends_on:
      - postgres
    ports:
      - "8006:8000"  

  # shadow-model-trainer:
  #   build: ./services/shadow-model-trainer
  #   ports:
  #     - "8007:8000"